
const FETCH_VIDEOS = "FETCH_VIDEOS";
const FETCH_VIDEOS_LOADER = "FETCH_VIDEOS_LOADER";
const FETCH_VIDEOS_ERROR = "FETCH_VIDEOS_ERROR";

const SAGA_FETCH_VIDEOS_LOADER = "SAGA_FETCH_VIDEOS_LOADER";
const SAGA_FETCH_VIDEOS="SAGA_FETCH_VIDEOS";
const SAGA_FETCH_VIDEOS_ERROR="SAGA_FETCH_VIDEOS_ERROR";


export{
    FETCH_VIDEOS,
    FETCH_VIDEOS_LOADER,
    FETCH_VIDEOS_ERROR,

    SAGA_FETCH_VIDEOS_LOADER,    
    SAGA_FETCH_VIDEOS,
    SAGA_FETCH_VIDEOS_ERROR
}